@startuml


!include <azure/AzureCommon>
!include <azure/Compute/AzureVirtualMachine>
!include <azure/Management/AzureResourceGroups>
!include <azure/Management/AzureRecoveryServiceVault>
!include <azure/Networking/AzureVirtualNetwork>
!include <azure/Networking/AzureSubnet>
!include <azure/Networking/AzureNetworkInterface>
!include <azure/Networking/AzurePublicIPAddress>

AzureResourceGroups(UKSouthResourceGroup, "UKSouthResourceGroup", "Resource Group", "Main resource group for the UK South region") {

  AzureVirtualNetwork(VNetUKSouth, "VNetUKSouth", "Virtual Network", "Virtual network for UK South region") {

  AzureSubnet(SubnetUKSouth, "SubnetUKSouth", "Subnet", "Subnet within UK South virtual network") {

    AzureNetworkInterface(MyUKSouthVM-nic, "MyUKSouthVM-nic", "Network Interface", "Network interface for the UK South VM") {
    }

    AzureVirtualMachine(MyUKSouthVM, "MyUKSouthVM", "Virtual Machine", "Linux server for the UK South region") {
    }

  }
 }



AzurePublicIPAddress(MyUKSouthVM-pip, "MyUKSouthVM-pip", "Public IP Address", "Public IP address for the UK South VM") {
}



AzureRecoveryServiceVault(MyRecoveryVault, "MyRecoveryVault", "Recovery Services Vault", "Recovery vault for Azure Site Recovery") {
}



}
@enduml