@startuml
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/all.puml
!includeurl AzurePuml/Networking/all.puml
!includeurl AzurePuml/Management/all.puml

rectangle "UKSouth" {
    AzureResourceGroups(UKSouthResourceGroup, "UKSouthResourceGroup", "Resource Group", "Main resource group for the UK South region") {
        AzureVirtualNetwork(VNetUKSouth, "VNetUKSouth", "Virtual Network", "Virtual network for the primary region") {
            AzureSubnet(SubnetUKSouth, "SubnetUKSouth", "Subnet", "Subnet in the primary region") {
                         AzureVirtualMachine(MyUKSouthVM, "MyUKSouthVM", "Virtual Machine", "Primary virtual machine") {
                         AzureNetworkInterface(NetworkInterfaceMyUKSouthVM, "NetworkInterfaceMyUKSouthVM", "Network Interface", "Network interface for the primary VM")
                         }
            }
        }
        
       
        

    }
}

rectangle "UKWest" {
    AzureResourceGroups(UKWestResourceGroup, "UKWestResourceGroup", "Resource Group", "Main resource group for the UK West region") {
        AzureVirtualNetwork(VNetUKWest, "VNetUKWest", "Virtual Network", "Virtual network for the secondary region") {
            AzureSubnet(SubnetUKWest, "SubnetUKWest", "Subnet", "Subnet in the secondary region") {

                rectangle "<color:red><$AzureVirtualMachine></color>\n Failover VM"as failover #FFFFFF
            }
        }
        
        AzureRecoveryServiceVault(RecoveryVault, "RecoveryVault", "Recovery Services Vault", "Vault for backup and disaster recovery")
        

    }
}
@enduml