resource_group_name   = "your-resource-group-name"
recovery_vault_name   = "your-recovery-vault-name"
recovery_vault_location = "East US"
recovery_vault_sku    = "RS0"
source_vm_resource_group = "your-source-vm-resource-group"
os_type               = "Linux"
protection_policy_id  = "your-protection-policy-id"
protected_vm_name     = "MyUKSouthVM"
source_vm_name        = "MyUKSouthVM":w